export const persons = [
  {
    name: "Sri.L.Hari Prakash",
    cfms_id: "14406143",
    email: "tarunbommali2810@gmail.com",
    designation: "Assistant Professor",
    department: "IT",
  },
  {
    name: "Vemuri KrishnaAnila",
    cfms_id: "15071465",
    email: "tyashwanthkumar1@gmail.com",
    designation: "Assistant Professor",
    department: "IT",
  },
  {
    name: "Sri.K.Srinivasa Rao",
    cfms_id: "14062301",
    email: "venkateshtaddi548@gmail.com",
    designation: "Assistant Professor",
    department: "IT",
  },
  // {
  //   name: "Dr.V.S.Vakula",
  //   cfms_id: "15040168",
  //   email: "hod.eee@jntukucev.ac.in",
  //   designation: "Professor & HOD",
  //   department: "EEE",
  // },
  // {
  //   name: "GURUNADHA",
  //   cfms_id: "1000221742",
  //   email: "gururavva.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Dr.P.Sreedevi",
  //   cfms_id: "1000218176",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Associate Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Smt.M.Sowbhagyalakshmi",
  //   cfms_id: "1000218160",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Dr.D.Rajya Lakshmi",
  //   cfms_id: "1000218133",
  //   email: "rajyalakshmi.cse@jntugvcev.edu.in",
  //   designation: "Professor",
  //   department: "CSE",
  // },
  // {
  //   name: "BABULU",
  //   cfms_id: "1000218115",
  //   email: "kapbbl@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "NALINI",
  //   cfms_id: "1000218101",
  //   email: "nalinib.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Dr.C.Neelima Devi",
  //   cfms_id: "1000218099",
  //   email: "cneelima.me@jntugvcev.edu.in",
  //   designation: "Associate Professor",
  //   department: "ME",
  // },
  // {
  //   name: "ANIL",
  //   cfms_id: "1000218088",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "HEMA",
  //   cfms_id: "1000218040",
  //   email: "mhema.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Sri.B.Tiriumala Rao",
  //   cfms_id: "1000218038",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "D.V.S.ROLANGI",
  //   cfms_id: "1000218036",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "ARUNAKUMARI",
  //   cfms_id: "1000218022",
  //   email: "hod.cse@jntugvcev.edu.in",
  //   designation: "Professor & HOD",
  //   department: "CSE",
  // },
  // {
  //   name: "BINDUMADHURI",
  //   cfms_id: "1000218016",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "APPALANAIDU",
  //   cfms_id: "1000218015",
  //   email: "ganaidu.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "PADMAJA",
  //   cfms_id: "1000218014",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "C.B.RAO",
  //   cfms_id: "1000217999",
  //   email: "cbraokoa.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "S.PRASAD",
  //   cfms_id: "1000217998",
  //   email: "ksprasad.me@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ME",
  // },
  // {
  //   name: "SRIKUMAR",
  //   cfms_id: "1000217981",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Dr.G.J.Naga Raju",
  //   cfms_id: "1000217979",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Associate Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Gogulamanda Jayasuma",
  //   cfms_id: "15166317",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Davala Rajesh",
  //   cfms_id: "1009385232",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "VenkataSatyaDurga ManoharSahu",
  //   cfms_id: "1009385221",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Chevala VenkataRamana",
  //   cfms_id: "1009385201",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Chodavarapu GiridharKumar",
  //   cfms_id: "1009385192",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "CIVIL",
  // },
  // {
  //   name: "Abdul Kurshid",
  //   cfms_id: "1009385191",
  //   email: "khurshid06@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "ME",
  // },
  // {
  //   name: "Saka Rajitha",
  //   cfms_id: "1009385181",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Addepalli VenkataSuryaGowtham",
  //   cfms_id: "1009385175",
  //   email: "gowthamaddepalli@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "ME",
  // },
  // {
  //   name: "Tallapragada Sai Datta Phanindranath",
  //   cfms_id: "1009385172",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "CIVIL",
  // },
  // {
  //   name: "Bula Ratna KumarAmbedkar",
  //   cfms_id: "1009385169",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "MET",
  // },
  // {
  //   name: "Mallela KomaleswaraRao",
  //   cfms_id: "1009385168",
  //   email: "komalmallela.me@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ME",
  // },
  // {
  //   name: "Shaik Karimulla",
  //   cfms_id: "1009385158",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "MET",
  // },
  // {
  //   name: "Kolli VenkataNaidu",
  //   cfms_id: "1009385128",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "MET",
  // },
  // {
  //   name: "Dasari JaganMohan",
  //   cfms_id: "1009385120",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "CIVIL",
  // },
  // {
  //   name: "Pilli SreenivasulaReddy",
  //   cfms_id: "1009385109",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Panigrahi SivaKumar",
  //   cfms_id: "1009385106",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Ramba BalaMuraliKrishna",
  //   cfms_id: "1009385097",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "CIVIL",
  // },
  // {
  //   name: "Azamira SivasankarNaik",
  //   cfms_id: "1009385089",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Y Chittemma",
  //   cfms_id: "1002894067",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Vana LakshmiPrasad",
  //   cfms_id: "1009385231",
  //   email: "vlprasad.cse@jntugvcev.edu.in",
  //   designation: "Assistant Professor",
  //   department: "CSE",
  // },
  // {
  //   name: "Bonthula Sridurga",
  //   cfms_id: "1009385213",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Manda ChinaRaju",
  //   cfms_id: "1009385212",
  //   email: "chinnaraju.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Mallampalli KrishnaPriya",
  //   cfms_id: "1009385211",
  //   email: "krishnapriya.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Jallu Sateesh",
  //   cfms_id: "1009385193",
  //   email: "sateeshjallu@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "B Manasa",
  //   cfms_id: "1009385182",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Suragala Ashok",
  //   cfms_id: "1009385176",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Botsa DharmaRao",
  //   cfms_id: "1009385174",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Kotla Swathi",
  //   cfms_id: "1009385173",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Kolli Srikanth",
  //   cfms_id: "1009385170",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Pynam Venkateswarulu",
  //   cfms_id: "1009385167",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Kaki VeerRaju",
  //   cfms_id: "1009385160",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Nammi SureshKumar",
  //   cfms_id: "1009385159",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Potula PavanKumar",
  //   cfms_id: "1009385157",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Molli GeethaMadhuriYadav",
  //   cfms_id: "1009385148",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "CSE",
  // },
  // {
  //   name: "Varanasi SantoshKumar",
  //   cfms_id: "1009385146",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Rajeti RojeSpandana",
  //   cfms_id: "1009385137",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Langoju KrishnaChaitanya",
  //   cfms_id: "1009385136",
  //   email: "chaitukanna326@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "ME",
  // },
  // {
  //   name: "Shaik Naseema",
  //   cfms_id: "1009385127",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "MET",
  // },
  // {
  //   name: "VeeraGanta VijayaSanthi",
  //   cfms_id: "1009385108",
  //   email: "vijayasanthi.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Arnuri Srinivasulu",
  //   cfms_id: "1009385107",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "MET",
  // },
  // {
  //   name: "Yerra VAmardeep",
  //   cfms_id: "1009385098",
  //   email: "jntugv.IT@gmail.com",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Vemulada NarayanaRao",
  //   cfms_id: "1009385090",
  //   email: "narayanarao.cse@jntugvcev.edu.in",
  //   designation: "Assistant Professor",
  //   department: "CSE",
  // },
  // {
  //   name: "Kollu VSatyanarayana",
  //   cfms_id: "1009385060",
  //   email: "kvsatyanarayana.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Banothu ChennaKesava",
  //   cfms_id: "1009385059",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "MET",
  // },
  // {
  //   name: "Tammineni Sirisha",
  //   cfms_id: "1009385058",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "EEE",
  // },
  // {
  //   name: "Madhumita Chanda",
  //   cfms_id: "1003102802",
  //   email: "N/A",
  //   designation: "Assistant Professor",
  //   department: "IT",
  // },
  // {
  //   name: "Kona Anusha Yadav",
  //   cfms_id: "1002846720",
  //   email: "anushayadav.ece@jntukucev.ac.in",
  //   designation: "Assistant Professor",
  //   department: "ECE",
  // },
  // {
  //   name: "Dr.G.Swami Naidu",
  //   cfms_id: "15152305",
  //   email: "gsnaidujntuk@gmail.com",
  //   designation: "Professor",
  //   department: "ME",
  // },
];

// Department mapping for reference:
// IT - Master of Computer Applications
// EEE - Electrical and Electronics Engineering
// ECE - Electronics and Communication Engineering
// CSE - Computer Science and Engineering
// ME - Mechanical Engineering
// IT - Information Technology
// CIVIL - Civil Engineering
// MET - Metallurgical Engineering