import { formatDate, formatTime } from './utility';

export const generatePlaintextFromSummary = (employee, summary, attendanceMetrics, config) => {
  const percentage = Number(summary.attendancePercentage ?? 0).toFixed(1);
  const workingDays = summary.workingDays || 0;
  const companyName = config?.companyName || 'APFRS';
  const systemName = config?.systemName || 'Attendance System';

  return [
    `╔══════════════════════════════════════════════════════════════╗`,
    `  ${companyName} ATTENDANCE REPORT`,
    `╚══════════════════════════════════════════════════════════════╝`,
    ``,
    `EMPLOYEE INFORMATION`,
    `────────────────────`,
    `Name:         ${employee.name}`,
    `Employee ID:  ${employee.cfmsId || employee.employeeId || 'N/A'}`,
    `Department:   ${employee.department || 'N/A'}`,
    `Designation:  ${employee.designation || 'N/A'}`,
    ``,
    `REPORT PERIOD`,
    `─────────────`,
    `Period Days:  ${workingDays} days`,
    `Working Days: ${workingDays}`,
    `Holidays:     ${summary.holidays || 0}`,
    `Report Date:  ${formatDate()}`,
    `Generated:    ${formatTime()}`,
    ``,
    `ATTENDANCE SUMMARY`,
    `──────────────────`,
    `Present Days:     ${summary.presentDays}`,
    `Absent Days:      ${summary.absentDays}`,
    `Leave Days:       ${summary.leaveDays || 0}`,
    `Late Arrivals:    ${attendanceMetrics.lateArrivals}`,
    `Half Days:        ${summary.halfDays || 0}`,
    `Total Hours:      ${summary.totalHours} hours`,
    `Attendance Rate:  ${percentage}%`,
    ``,
    `PERFORMANCE METRICS`,
    `──────────────────`,
    `Total Records:    ${attendanceMetrics.totalRecords}`,
    `Avg Late Time:    ${attendanceMetrics.averageLateTime} minutes`,
    `Early Departures: ${attendanceMetrics.earlyDepartures}`,
    `Missed Checkouts: ${attendanceMetrics.missedCheckouts}`,
    ``,
    `REMARKS`,
    `───────`,
    `${employee.name} has recorded ${percentage}% attendance for ${workingDays} working days.`,
    `Present on ${summary.presentDays} days, absent on ${summary.absentDays} days.`,
    `Total working hours: ${summary.totalHours} hours.`,
    ``,
    `════════════════════════════════════════════════════════════════`,
    `This is an automated report generated by the`,
    `${systemName} attendance system.`,
    ``,
    `© ${new Date().getFullYear()} ${companyName}. All rights reserved.`,
    `════════════════════════════════════════════════════════════════`,
  ].join('\n');
};

export const generateAttendanceReport = (employee, summary, config = null, monthNumber = 11, year = new Date().getFullYear()) => {
  const totalPeriodDays = summary.totalDays || 0;
  const present = Number(summary.presentDays || 0);
  const fallbackPercentage = totalPeriodDays > 0
    ? (present / totalPeriodDays) * 100
    : 0;
  const rawPercentage = Number(summary?.attendancePercentage);
  const calculatedPercentage = Number.isFinite(rawPercentage)
    ? rawPercentage.toFixed(1)
    : fallbackPercentage.toFixed(1);

  const companyName = config?.companyName || 'APFRS';
  const systemName = config?.systemName || 'Attendance System';

  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const periodLabel = `${monthNames[monthNumber - 1]} ${year}`;
  const workingDaysCount = summary.workingDays || totalPeriodDays;

  // Calculate attendance metrics
  const attendanceMetrics = calculateAttendanceMetrics(employee.attendance || []);

  return {
    percentage: calculatedPercentage,
    attendanceMetrics,
    reportId: `${employee.cfmsId || employee.employeeId || 'N/A'}-${Date.now().toString(36).toUpperCase()}`,
    totalPeriodDays,
    calculatedPercentage,
    workingDaysCount,
    periodLabel,
    companyName,
    systemName
  };
};

const calculateAttendanceMetrics = (attendance = []) => {
  const validRecords = attendance.filter(record =>
    record.status && record.status.toString().toUpperCase() !== 'ABSENT'
  );

  let totalLateMinutes = 0;
  let lateCount = 0;
  let earlyDepartures = 0;
  let missedCheckouts = 0;

  validRecords.forEach(record => {
    if (record.inTime && record.inTime !== '-' && record.inTime !== '') {
      const [hours, minutes] = record.inTime.split(':').map(Number);
      const arrivalMinutes = hours * 60 + minutes;
      const expectedArrival = 9 * 60;

      if (arrivalMinutes > expectedArrival + 15) {
        totalLateMinutes += (arrivalMinutes - expectedArrival);
        lateCount++;
      }
    }

    if (record.outTime && record.outTime !== '-' && record.outTime !== '') {
      const [hours, minutes] = record.outTime.split(':').map(Number);
      const departureMinutes = hours * 60 + minutes;
      const expectedDeparture = 17 * 60;

      if (departureMinutes < expectedDeparture - 15) {
        earlyDepartures++;
      }
    } else {
      missedCheckouts++;
    }
  });

  const avgLateTime = lateCount > 0 ? totalLateMinutes / lateCount : 0;

  return {
    totalRecords: validRecords.length,
    lateArrivals: lateCount,
    averageLateTime: Math.round(avgLateTime),
    earlyDepartures,
    missedCheckouts,
  };
};