/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConsolidatedRouteImport } from './routes/consolidated'
import { Route as DetailedRouteImport } from './routes/detailed'
import { Route as FacultyProfileRouteImport } from './routes/faculty-profile'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportsMonthYearRouteImport } from './routes/reports.$month.$year'
import { Route as StatusDashboardRouteImport } from './routes/status-dashboard'
import { Route as EmailConfigRouteImport } from './routes/email-config'
import { Route as FacultyNewRouteImport } from './routes/faculty.new'
import { Route as FacultyIdEditRouteImport } from './routes/faculty.$id.edit'
import { Route as EditCalendarRouteImport } from './routes/edit.calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidatedRoute = ConsolidatedRouteImport.update({
  id: '/consolidated',
  path: '/consolidated',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailedRoute = DetailedRouteImport.update({
  id: '/detailed',
  path: '/detailed',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyProfileRoute = FacultyProfileRouteImport.update({
  id: '/faculty-profile',
  path: '/faculty-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsMonthYearRoute = ReportsMonthYearRouteImport.update({
  id: '/reports/$month/$year',
  path: '/reports/$month/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusDashboardRoute = StatusDashboardRouteImport.update({
  id: '/status-dashboard',
  path: '/status-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfigRoute = EmailConfigRouteImport.update({
  id: '/email-config',
  path: '/email-config',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyNewRoute = FacultyNewRouteImport.update({
  id: '/faculty/new',
  path: '/faculty/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIdEditRoute = FacultyIdEditRouteImport.update({
  id: '/faculty/$id/edit',
  path: '/faculty/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EditCalendarRoute = EditCalendarRouteImport.update({
  id: '/edit/calendar',
  path: '/edit/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/calendar': typeof CalendarRoute
  '/consolidated': typeof ConsolidatedRoute
  '/detailed': typeof DetailedRoute
  '/faculty-profile': typeof FacultyProfileRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/reports/$month/$year': typeof ReportsMonthYearRoute
  '/status-dashboard': typeof StatusDashboardRoute
  '/email-config': typeof EmailConfigRoute
  '/faculty/new': typeof FacultyNewRoute
  '/faculty/$id/edit': typeof FacultyIdEditRoute
  '/edit/calendar': typeof EditCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/calendar': typeof CalendarRoute
  '/consolidated': typeof ConsolidatedRoute
  '/detailed': typeof DetailedRoute
  '/faculty-profile': typeof FacultyProfileRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/reports/$month/$year': typeof ReportsMonthYearRoute
  '/status-dashboard': typeof StatusDashboardRoute
  '/email-config': typeof EmailConfigRoute
  '/faculty/new': typeof FacultyNewRoute
  '/faculty/$id/edit': typeof FacultyIdEditRoute
  '/edit/calendar': typeof EditCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/calendar': typeof CalendarRoute
  '/consolidated': typeof ConsolidatedRoute
  '/detailed': typeof DetailedRoute
  '/faculty-profile': typeof FacultyProfileRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/reports/$month/$year': typeof ReportsMonthYearRoute
  '/status-dashboard': typeof StatusDashboardRoute
  '/email-config': typeof EmailConfigRoute
  '/faculty/new': typeof FacultyNewRoute
  '/faculty/$id/edit': typeof FacultyIdEditRoute
  '/edit/calendar': typeof EditCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/calendar'
    | '/consolidated'
    | '/detailed'
    | '/faculty-profile'
    | '/import'
    | '/login'
    | '/reports'
    | '/reports/$month/$year'
    | '/status-dashboard'
    | '/email-config'
    | '/faculty/new'
    | '/faculty/$id/edit'
    | '/edit/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/calendar'
    | '/consolidated'
    | '/detailed'
    | '/faculty-profile'
    | '/import'
    | '/login'
    | '/reports'
    | '/reports/$month/$year'
    | '/status-dashboard'
    | '/email-config'
    | '/faculty/new'
    | '/faculty/$id/edit'
    | '/edit/calendar'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/calendar'
    | '/consolidated'
    | '/detailed'
    | '/faculty-profile'
    | '/import'
    | '/login'
    | '/reports'
    | '/reports/$month/$year'
    | '/status-dashboard'
    | '/email-config'
    | '/faculty/new'
    | '/faculty/$id/edit'
    | '/edit/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  CalendarRoute: typeof CalendarRoute
  ConsolidatedRoute: typeof ConsolidatedRoute
  DetailedRoute: typeof DetailedRoute
  FacultyProfileRoute: typeof FacultyProfileRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  ReportsMonthYearRoute: typeof ReportsMonthYearRoute
  StatusDashboardRoute: typeof StatusDashboardRoute
  EmailConfigRoute: typeof EmailConfigRoute
  FacultyNewRoute: typeof FacultyNewRoute
  FacultyIdEditRoute: typeof FacultyIdEditRoute
  EditCalendarRoute: typeof EditCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidated': {
      id: '/consolidated'
      path: '/consolidated'
      fullPath: '/consolidated'
      preLoaderRoute: typeof ConsolidatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detailed': {
      id: '/detailed'
      path: '/detailed'
      fullPath: '/detailed'
      preLoaderRoute: typeof DetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty-profile': {
      id: '/faculty-profile'
      path: '/faculty-profile'
      fullPath: '/faculty-profile'
      preLoaderRoute: typeof FacultyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$month/$year': {
      id: '/reports/$month/$year'
      path: '/reports/$month/$year'
      fullPath: '/reports/$month/$year'
      preLoaderRoute: typeof ReportsMonthYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-dashboard': {
      id: '/status-dashboard'
      path: '/status-dashboard'
      fullPath: '/status-dashboard'
      preLoaderRoute: typeof StatusDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-config': {
      id: '/email-config'
      path: '/email-config'
      fullPath: '/email-config'
      preLoaderRoute: typeof EmailConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/new': {
      id: '/faculty/new'
      path: '/faculty/new'
      fullPath: '/faculty/new'
      preLoaderRoute: typeof FacultyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$id/edit': {
      id: '/faculty/$id/edit'
      path: '/faculty/$id/edit'
      fullPath: '/faculty/$id/edit'
      preLoaderRoute: typeof FacultyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/calendar': {
      id: '/edit/calendar'
      path: '/edit/calendar'
      fullPath: '/edit/calendar'
      preLoaderRoute: typeof EditCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  CalendarRoute: CalendarRoute,
  ConsolidatedRoute: ConsolidatedRoute,
  DetailedRoute: DetailedRoute,
  FacultyProfileRoute: FacultyProfileRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  ReportsMonthYearRoute: ReportsMonthYearRoute,
  StatusDashboardRoute: StatusDashboardRoute,
  EmailConfigRoute: EmailConfigRoute,
  FacultyNewRoute: FacultyNewRoute,
  FacultyIdEditRoute: FacultyIdEditRoute,
  EditCalendarRoute: EditCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
